### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by qzqs** [li-yu/Huahui-Android#1]
private void sortData() {
        final Collator collator = Collator.getInstance();
        Collections.sort(adapter.getData(), new Comparator<Word>() {
            @Override
            public int compare(Word o1, Word o2) {
                return collator.compare(o1.getName(), o2.getName());
            }
        });
    }

作者这一步是排序么？具体有什么作用？

**Comment by li-yu** [comment]
因为 App 提供了一个新增单词的功能，希望新单词插入在合适的位置，所有进行了重新排序。
